---
title: "Accessing elevation data in R with the elevatr package"
author: "Jeffrey W. Hollister"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Accessing elevation data in R with the elevatr package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

Elevation data is used for a wide array of applications, including, for example, visualization, hydrology, and ecological modelling.  Gaining access to this data in R has not had a single interface and was made available through functions across many packages or required local access to the data.  This is no longer required as a variety of APIs now exist that provide programmatic access to elevation data.  The `elevatr` package was written to standarize access to elevation data from web APIs.  This introductory vignette provides details on how to use `elevatr` to access elevation data and provides a bit of detail on the source data it accesses.

There are currently four endpoints that `elevatr` accesses.  For point elevation data it uses USGS Elevation Point Query Service and Mapzen Elevation Service and to access raster elevation data (e.g. a DEM) it uses Mapzen Terrain Service, and the Amazon Web Services Terrain Tiles.

# Get Point Elevation Data

Point elevation is accesses from `get_elev_point()`.  This function takes either a data.frame of XY locations or a SpatialPoints/SpatialPointsDataFrame as input and then fetches the reported elevation for that location.  As mentioned there are two services that provide this information.  Details and use for those are provided below.

## Mapzen Elevation Service 

<https://mapzen.com/documentation/elevation/elevation-service/>

### API Keys

## USGS Elevation Point Query Service 

<http://ned.usgs.gov/epqs/>

# Get Raster Elevation Data

## Mapzen Terrain Tile Service

<https://mapzen.com/documentation/terrain-tiles/>

### API Keys

## Terrain Tiles on Amazon Web Services (AWS)

<https://aws.amazon.com/public-datasets/terrain/>

<!--
Begining of vignette for elevatr package

```{r, eval=F}
library(sp)
library(elevatr)
library(raster)
dim_df <- data.frame(lat=NA,z=NA,x_res=NA,y_res=NA)
ct <- 1
for(i in seq(0,60,10)){
  xdf <- SpatialPoints(coordinates(data.frame(0,i)),CRS("+proj=longlat"))
  xdf_alb <- spTransform(xdf,CRS("+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"))
  for(j in 0:14){
    x <- get_elev_raster(xdf_alb,z=j)
    dim_df[ct,]<-data.frame(i,j,res(x)[1],res(x)[2])
    ct <- ct + 1
  }
}
dim_df
```
--!>